DevKor-github/team-c-back

src/main/java/devkor/com/teamcback/domain/navigate/service/OuterRouteService.java
외부경로 중복 데이터 제거
OuterRouteService에서 데이터 형식 변화로 인해 생겨날 수 있는 중복 데이터 제거
=> Fix: 외부경로 중복 데이터 제거

src/main/java/devkor/com/teamcback/domain/search/dto/response/GetRoomDetailRes.java
maskIndex null값도 반환하도록 수정
- 전체에 적용되어 있던 @JsonInclude(Include.NON_NULL)을 maskIndex만 제외하고 공통되지 않는 필드 위에 각각 추가했습니다!
- 추가로 아래에 operatingTime 이 imageUrl로 들어가있길래 수정했습니다..!
-
=> Fix: maskIndex null값도 반환하도록 수정

src/main/java/devkor/com/teamcback/domain/bookmark/service/CategoryService.java, src/main/java/devkor/com/teamcback/domain/search/contoller/SearchController.java, src/main/java/devkor/com/teamcback/domain/search/dto/response/GetBuildingDetailRes.java, src/main/java/devkor/com/teamcback/domain/search/dto/response/SearchBuildingDetailRes.java, src/main/java/devkor/com/teamcback/domain/search/dto/response/SearchMaskIndexByPlaceRes.java, src/main/java/devkor/com/teamcback/domain/search/dto/response/SearchPlaceDetailRes.java, src/main/java/devkor/com/teamcback/domain/search/service/SearchService.java
1. 전체 빌딩 조회
-> 건물 이름 수정, 운영 정보(임시값), 편의시설 타입 추가
+) nextBuildingTime : 현재 열려있으면 닫는 시간, 닫혀있으면 다음으로 여는 시간 반환하는 것으로 구상하였습니다. 
2. 건물 상세 정보 조회
->건물 사진 url, 운영 정보(임시값) 추가
3. placeType, placeId를 받은 후 건물id, 층, mask Index를 반환하는 API 추가
4. 장소(교실 or 편의시설) 상세 정보 조회 API 추가
-> placeType과 placeId를 입력하면 상세 정보 조회 가능
-> bookmarked 여부 확인 가능
-> 운영 정보(임시값) 추가, nextPlaceTime은 위의 nextBuildingTime과 동일
->실내면 건물명+장소명, 야외면 장소명만 반환
=> Search API 수정 & 추가

src/main/java/devkor/com/teamcback/domain/navigate/controller/RouteController.java, src/main/java/devkor/com/teamcback/domain/navigate/dto/response/GetRouteRes.java, src/main/java/devkor/com/teamcback/domain/navigate/entity/LinkedBuildingData.java, src/main/java/devkor/com/teamcback/domain/navigate/service/RouteService.java
길찾기 기능 수정 및 보수
*경로가 찾아지지 않을 경우 오류 메시지를 담게 리턴되도록 GetRouteRes 기능 추가
*RouteController의 파라미터에서 barrierFree 제거. 대신, 아예 그냥 탐색과 계단 이용 안 한 barrierFree 경로로 2개의 경로가 리턴되도록 RouteController 수정
*노드 데이터가 들어간 것 확인된 하나스퀘어와 과학도서관 연결 정보 LinkedBuildingData에 등록, 경로 탐색 원활한 것 확인
*getGraph 수정, 이제 인접 노드가 없어도(adjacentNode나 distance가 null이어도) 경로 탐색 가능. 추가적으로, adjacentNode와 distance의 길이가 다른 경우에도 일단 길찾기에 이용하지 않도록 수정. 주석 달린 코드 통해 그와 관련된 오류 있는지 확인 가능.
- route api 리턴 형식 변경: path가 이제는 경로 묶음의 리스트를 리턴합니다.
=> fix 길찾기 기능 수정 및 보수

src/main/java/devkor/com/teamcback/domain/building/entity/Building.java, src/main/java/devkor/com/teamcback/domain/building/repository/BuildingRepository.java, src/main/java/devkor/com/teamcback/domain/classroom/entity/Classroom.java, src/main/java/devkor/com/teamcback/domain/classroom/repository/ClassroomNicknameRepository.java, src/main/java/devkor/com/teamcback/domain/classroom/repository/ClassroomRepository.java, src/main/java/devkor/com/teamcback/domain/facility/entity/Facility.java, src/main/java/devkor/com/teamcback/domain/facility/repository/FacilityRepository.java, src/main/java/devkor/com/teamcback/domain/operatingtime/sceduler/OperatingScheduler.java, src/main/java/devkor/com/teamcback/domain/operatingtime/service/OperatingService.java, src/main/java/devkor/com/teamcback/domain/search/service/SearchService.java
운영 조건에 포함되지 않는 시설의 운영 여부가 바뀌지 않는 오류 수정했습니다.
- 운영 조건에 포함되지 않는 건물의 운영 여부는 false로, 강의실과 편의시설은 건물의 운영여부를 따라가도록 수정
- 운영 시간 스케줄러가 돌아갈 때 노드까지 검색되어 오래 걸리는 문제를 해결하기 위해 건물/강의실/편의시설이 노드를 지연로딩하도록 변경 -> 기존 api들이 정상적으로 돌아가는지 확인했으나 문제가 생길 수 있습니다...
- 강의실 검색 시 '검색어가 포함되는 별명 검색 -> 건물과 일치하는지 확인' 부분이 오래 걸리는 것 같아 '건물에 해당하는 강의실 검색 -> 강의실과 검색어를 포함하는 별명 검색' 순서로 변경하였습니다.
-
=> 운영시간 오류 및 강의실 검색 수정

src/main/java/devkor/com/teamcback/domain/classroom/repository/ClassroomNicknameRepository.java, src/main/java/devkor/com/teamcback/domain/search/contoller/SearchController.java, src/main/java/devkor/com/teamcback/domain/search/service/SearchService.java
<수정사항>
* 공백 기준 첫번째 값을 건물로 받아서 검색하도록 수정
* 검색 결과 가중치 수정 (Score 사용)
-빌딩 → 1000점
-편의시설(type리스트에 있으면)→500점
-편의시설(리스트X) → 0점
-강의실→0점
~> (100 - 첫 글자가 등장하는 위치 index) 를 각각 더해서 최종 점수 도출 (+괄호 내부의 값에 대해 가중치 부여)
* 검색 결과 개수 제한 추가
-한글자만 입력 시 DB가 커짐에 따라 시간이 매우 많이 소요됨 (첫 글자 입력 후 항상 오랜 시간이 소요)
-building 제외 classroom의 경우 DB에서부터 30개씩만 가져오도록 제한
<API>
- 기존의 것 포함
- 새로운 통합 검색은 /search/test 로 수정했습니다.
=> 통합검색 기능 수정

src/main/java/devkor/com/teamcback/domain/facility/entity/Facility.java, src/main/java/devkor/com/teamcback/domain/search/contoller/SearchController.java, src/main/java/devkor/com/teamcback/domain/search/dto/response/GlobalSearchRes.java, src/main/java/devkor/com/teamcback/domain/search/service/SearchService.java
1. URL 수정 (/search로 변경), 기존 검색 로직 삭제
2. GlobalSearchRes DTO 수정
-야외태그(Ex. 라운지) → id = null, buildingId = 0
-내부태그(Ex. 과학도서관 라운지) → id = null, buildingId = 건물ID
-특정시설(Ex. 우당교양관 우당 박종구 라운지) → id = 편의시설ID, buildingId = null
+) id, buildingId는 null이어도 반환하도록 수정
3. 검색 기준에 괄호 외에도 “대학”, “관” 추가 → 생명과학관서관 등도 위에 뜨게 됨
4. 건물명이 맨 뒤에 오는 경우에도 검색 가능
→검색 결과 중복 문제 -> equals(), hashCode() 메서드 오버라이딩
5. 검색 시 항상 건물 포함
→ 건물명 외의 키워드가 존재하는 경우, 건물은 맨 밑에 뜨도록 수정
- 키워드에 공백이 있는 경우, 공백 기준 둘 모두를 검색하여 indexScore을 계산하도록 수정
- static final 상수 추가
- 특수명 Facility만 가진 경우의 내부 태그 검색을 위한 검색어도 나오도록 수정 (Ex. 이전→ 해송법학도서관 라운지는 나오지 않음)
=> 통합 검색 기능 수정

src/main/java/devkor/com/teamcback/domain/search/contoller/SearchController.java, src/main/java/devkor/com/teamcback/domain/search/dto/response/SearchBuildingFacilityListRes.java, src/main/java/devkor/com/teamcback/domain/search/dto/response/SearchFacilityListRes.java, src/main/java/devkor/com/teamcback/domain/search/dto/response/SearchFacilityRes.java, src/main/java/devkor/com/teamcback/domain/search/service/SearchService.java
특정 편의시설 리스트 조회를 위한 API 추가
- 기존의 특정 편의시설이 존재하는 건물 조회("/api/search/facilities")를 모든 건물 조회 API("/api/search/buildings")와 통일
-> 파라미터가 존재하지 않으면(/api/search/buildings) 모든 건물 조회 (야외 제외)
-> 파라미터가 존재하는 경우(/api/search/buildings?type=CAFE) 해당 편의시설을 가진 건물 조회 (야외 포함)
- 특정 편의시설 리스트 조회를 위한 API 추가 (/api/search/facilities?type=CAFE)
- 편의시설 타입을 카페, 식당, 편의점으로 제한하지는 않았으나 카페, 식당, 편의점에 해당하는 편의시설만 DB에 위경도 값을 넣음
-
=> 특정 편의시설 리스트 조회

src/main/java/devkor/com/teamcback/domain/operatingtime/sceduler/OperatingScheduler.java, src/main/java/devkor/com/teamcback/domain/operatingtime/service/OperatingService.java, src/main/java/devkor/com/teamcback/domain/suggestion/entity/SuggestionType.java, src/main/java/devkor/com/teamcback/global/response/ResultCode.java
next time의 경우 중간에 쉬는 시간이 있는 경우를 반영하지 못해서 수정
- 스케줄러가 낮 동안에는 10분마다, 밤에는 30분마다 작동하도록 수정
- 중간에 쉬는 시간이 있는 경우 next time을 다시 시작하는 시간, 다음 쉬는 시간 등을 반환할 수 있도록 운영 조건이 있는 장소의 operatingtime을 주기적으로 수정하도록 변경
- 건의 종류 수정
-
=> Fix/operatingtime 쉬는 시간 고려하도록 수정

src/main/java/devkor/com/teamcback/domain/oauth2/service/OAuth2Service.java, src/main/java/devkor/com/teamcback/domain/user/controller/UserController.java, src/main/java/devkor/com/teamcback/domain/user/dto/response/GetUserInfoRes.java, src/main/java/devkor/com/teamcback/domain/user/dto/response/ModifyUsernameRes.java, src/main/java/devkor/com/teamcback/domain/user/entity/Level.java, src/main/java/devkor/com/teamcback/domain/user/entity/ProfileImage.java, src/main/java/devkor/com/teamcback/domain/user/entity/User.java, src/main/java/devkor/com/teamcback/domain/user/repository/UserRepository.java, src/main/java/devkor/com/teamcback/domain/user/service/UserService.java, src/main/java/devkor/com/teamcback/global/response/ResultCode.java
- 사용자명 수정 기능 추가
- 프로필 이미지 관련 수정
- 마이페이지 정보 조회 시 level의 반환타입을 int로 수정 (FE 요청)
<사용자명>
- 빈 스트링 / 다른 사용자가 사용중인 별명 / 본인의 기존 별명과 동일한 별명을 받은 경우 예외가 발생합니다.
<프로필 이미지>
- application.yml에 각 레벨 이미지 경로를 추가하였습니다. 자세한 사항은 BE 관련 명세의 해당 부분을 참고해주세요!
- 각 레벨별 프로필 이미지는 제가 임시로 그려서 넣어뒀습니다. 나중에 디자인 완성되면 수정하겠습니다!
- level과 관련된 계산 로직들을 모두 UserService 파일로 이동시켰습니다.
- Bean과 관련된 문제가 있어서 아예 profileUrl을 받아오는 class를 따로 생성하였습니다!
- tb_user의 profileUrl을 삭제하니까 로그인에 오류가 생겨서 해당 PR을 머지한 후에 제거하도록 하겠습니다. User Entity의 생성자가 달라서 오류가 발생하는 것 같아요!
=> User 관련 기능 추가 및 수정

src/main/java/devkor/com/teamcback/domain/bookmark/dto/request/CreateBookmarkReq.java, src/main/java/devkor/com/teamcback/domain/bookmark/dto/response/GetBookmarkRes.java, src/main/java/devkor/com/teamcback/domain/bookmark/entity/Bookmark.java, src/main/java/devkor/com/teamcback/domain/bookmark/entity/UserBookmarkLog.java, src/main/java/devkor/com/teamcback/domain/bookmark/repository/BookmarkRepository.java, src/main/java/devkor/com/teamcback/domain/bookmark/repository/UserBookmarkLogRepository.java, src/main/java/devkor/com/teamcback/domain/bookmark/service/CategoryService.java, src/main/java/devkor/com/teamcback/domain/search/service/SearchService.java, src/main/java/devkor/com/teamcback/domain/suggestion/controller/SuggestionController.java, src/main/java/devkor/com/teamcback/domain/suggestion/dto/response/GetSuggestionRes.java, src/main/java/devkor/com/teamcback/domain/suggestion/entity/Suggestion.java, src/main/java/devkor/com/teamcback/domain/suggestion/service/SuggestionService.java, src/main/java/devkor/com/teamcback/domain/user/entity/Level.java, src/main/java/devkor/com/teamcback/domain/user/entity/User.java, src/main/java/devkor/com/teamcback/domain/user/service/UserService.java
- level 기준 점수 수정
-  bookmark 추가 시 User Score 증가 (+1점)
- tb_bookmark의 placeId 컬럼/변수를 locationId로 수정했습니다 (혼란 방지용)
- tb_suggestion에 userId 추가
- 즐겨찾기 취소에 대한 점수 회수는 없지만, 동일 건물/시설물에 대한 즐겨찾기 점수 상승은 1회만 가능.
- 동일 건물에 대해 취소했다 다시 즐겨찾기해도 추가 점수상승 없음
- tb_user_bookmark_log에 관련 정보 저장하는 방식을 사용했습니다
- 건의 생성 시 로그인 필요, 점수 3점 증가
- 전체 건의 조회 시 userId도 조회 가능
=> Fix: bookmark 추가에 따른 User Score 증가 로직 추가

src/main/java/devkor/com/teamcback/domain/operatingtime/entity/OperatingTime.java, src/main/java/devkor/com/teamcback/domain/operatingtime/sceduler/OperatingScheduler.java, src/main/java/devkor/com/teamcback/domain/operatingtime/service/OperatingService.java, src/main/java/devkor/com/teamcback/domain/place/entity/Place.java
Operating time의 운영 시작 시간, 종료 시간의 타입을 int -> localTime으로 수정
- Operating time의 운영 시작 시간, 종료 시간의 타입을 int -> localTime으로 수정
- 장소의 operatingTime이 "00:00-00:00"형식이 아닌 문자열인 경우 building의 operatingTime을 가져오도록 수정
- 해당 PR 머지 후 operatingTime의 기존 필드를 삭제할 예정입니다.
=> Operating time 시간 타입 변경

src/main/java/devkor/com/teamcback/domain/search/service/SearchService.java
buildings/{buildingId}/floor/{floor}/rooms
- 동일 코드가 두번 들어있어서 제거하였습니다.
=> Fix:search 중복 제거

src/main/java/devkor/com/teamcback/domain/operatingtime/entity/DayOfWeek.java, src/main/java/devkor/com/teamcback/domain/operatingtime/scheduler/HolidayScheduler.java, src/main/java/devkor/com/teamcback/domain/operatingtime/scheduler/OperatingScheduler.java, src/main/java/devkor/com/teamcback/domain/operatingtime/service/OperatingService.java, src/main/java/devkor/com/teamcback/domain/routes/entity/NodeType.java
건물 다음 운영 시간을 찾는 로직 오류 수정
ex. 일요일 운영 시간이 시간 형식이 아닌 문자열일 때 : 평일이 아닌 토요일 운영 시간을 가져옴
- 건물 다음 운영 시간을 찾는 로직 오류 수정
- 가독성을 위해 DayOfWeek enum 수정
- 길찾기 오류 방지를 위해 nodeType 수정
- 스케줄러 오타 수정
- 정보 없는 건물 리스트 추가
-
=> Fix: 건물 다음 운영 시간을 찾는 로직 오류 수정

src/main/java/devkor/com/teamcback/domain/bookmark/controller/BookmarkController.java, src/main/java/devkor/com/teamcback/domain/bookmark/controller/CategoryController.java, src/main/java/devkor/com/teamcback/domain/bookmark/dto/request/CreateBookmarkReq.java, src/main/java/devkor/com/teamcback/domain/bookmark/dto/response/CreateBookmarkRes.java, src/main/java/devkor/com/teamcback/domain/bookmark/dto/response/GetCategoryListRes.java, src/main/java/devkor/com/teamcback/domain/bookmark/dto/response/GetCategoryRes.java, src/main/java/devkor/com/teamcback/domain/bookmark/entity/Bookmark.java, src/main/java/devkor/com/teamcback/domain/bookmark/entity/Category.java, src/main/java/devkor/com/teamcback/domain/bookmark/entity/CategoryBookmark.java, src/main/java/devkor/com/teamcback/domain/bookmark/repository/BookmarkRepository.java, src/main/java/devkor/com/teamcback/domain/bookmark/repository/CategoryBookmarkRepository.java, src/main/java/devkor/com/teamcback/domain/bookmark/service/BookmarkService.java, src/main/java/devkor/com/teamcback/domain/bookmark/service/CategoryService.java, src/main/java/devkor/com/teamcback/domain/search/contoller/SearchController.java, src/main/java/devkor/com/teamcback/domain/search/dto/response/SearchFloorInfoRes.java, src/main/java/devkor/com/teamcback/domain/search/service/SearchService.java
카테고리 및 즐겨찾기 수정
- 카테고리, 즐겨찾기 다대다 연관관계로 수정
- 카테고리, 즐겨찾기의 컨트롤러, 서비스 분리
- 즐겨찾기 생성 및 수정 시 카테고리를 리스트로 받도록 수정
- 카테고리 조회 시 장소 정보를 함께 보내면 해당 장소의 즐겨찾기 id, 해당 즐겨찾기의 카테고리 포함 여부 등의 정보도 반환하도록 추가
- 즐겨찾기 업데이트 시 카테고리를 선택하지 않으면 해당 즐겨찾기가 삭제됩니다.
- 즐겨찾기에서 장소 id와 type이 같은 경우 기존의 즐겨찾기를 사용합니다.
- 카테고리 내에서 즐겨찾기를 삭제하였는데 더 이상 그 즐겨찾기에 해당하는 카테고리가 없는 경우 즐겨찾기가 삭제됩니다.
=> 카테고리 및 즐겨찾기 수정

src/main/java/devkor/com/teamcback/global/security/SecurityConfig.java
Fix: API 권한 제한
- 고연전, 로그인 관련 API는 허용하고 나머지는 로그인이 필요하도록 수정
- 관리자 관련 API는 관리자만 가능
- 노드 관리 툴 수정 예정
=> Fix: API 권한 제한

src/main/java/devkor/com/teamcback/domain/koyeon/controller/KoyeonController.java, src/main/java/devkor/com/teamcback/domain/koyeon/dto/response/SearchFreePubRes.java, src/main/java/devkor/com/teamcback/domain/koyeon/repository/MenuRepository.java, src/main/java/devkor/com/teamcback/domain/koyeon/repository/TagMenuRepository.java, src/main/java/devkor/com/teamcback/domain/koyeon/service/KoyeonService.java, src/main/java/devkor/com/teamcback/global/response/ResultCode.java
태그검색 API 추가
- 파라미터가 없으면 전체 주점 조회
- 파라미터(태그 ID)가 있으면 해당 태그를 가진 메뉴의 가게와 메뉴 반환
-
=> Feat: 태그검색 API

src/main/java/devkor/com/teamcback/domain/koyeon/dto/response/GlobalPubSearchRes.java, src/main/java/devkor/com/teamcback/domain/koyeon/dto/response/SearchFreePubInfoRes.java, src/main/java/devkor/com/teamcback/domain/koyeon/dto/response/SearchFreePubRes.java, src/main/java/devkor/com/teamcback/global/security/SecurityConfig.java
편의성과 추후 주점 길찾기를 위해 길찾기와 검색 API의 경우 GET 요청은 허용하도록 SecurityConfig를 수정했습니다.
- SecurityConfig 수정: '/api/search/\*\*', '/api/routes/\*\*' 에 대하여 GET 요청 허용
- dto에 nodeId 추가
-
=> SecurityConfig api 권한 수정

src/main/java/devkor/com/teamcback/domain/bookmark/entity/CategoryBookmark.java, src/main/java/devkor/com/teamcback/domain/bookmark/repository/CategoryBookmarkRepository.java, src/main/java/devkor/com/teamcback/domain/bookmark/repository/CategoryRepository.java, src/main/java/devkor/com/teamcback/domain/bookmark/repository/UserBookmarkLogRepository.java, src/main/java/devkor/com/teamcback/domain/bookmark/service/CategoryService.java, src/main/java/devkor/com/teamcback/domain/suggestion/entity/Suggestion.java, src/main/java/devkor/com/teamcback/domain/suggestion/repository/SuggestionRepository.java, src/main/java/devkor/com/teamcback/domain/user/controller/UserController.java, src/main/java/devkor/com/teamcback/domain/user/dto/response/DeleteUserRes.java, src/main/java/devkor/com/teamcback/domain/user/service/UserService.java
회원 탈퇴 기능 추가
- 회원 탈퇴 시 기존 데이터를 모두 삭제하고 회원을 삭제
- 카테고리 삭제 시 즐겨찾기가 삭제되지 않는 오류 수정
- 회원 탈퇴 후 FE에서 토큰 처리 및 로그인 화면으로 이동하면 될 것 같아서 따로 토큰에 대한 처리는 하지 않았습니다.
=> Feat: 회원 탈퇴 기능 추가

src/main/java/devkor/com/teamcback/domain/routes/controller/RouteController.java, src/main/java/devkor/com/teamcback/domain/routes/service/RouteService.java
dev 기준으로 코드 수정하는 김에 그냥 버그를 수정해서 정상적인 탐색이 가능하도록 했습니다.
- 버그 탐색 및 수정으로 정상적인 일반 경로/배리어프리 경로 이중 탐색 가능
- 두 경로 중 하나가 없을 때, 에러코드 리턴이 아닌 description=1, 나머지 모두 빈 리스트 리턴하도록 함
- 추후 프론트엔드 작업 시 파라미터 conditions에 제한사항 넣기만 하면 즉시 이용 가능
-
=> Fix: routing bugfix

src/main/java/devkor/com/teamcback/domain/suggestion/controller/SuggestionController.java, src/main/java/devkor/com/teamcback/domain/suggestion/service/SuggestionService.java, src/main/java/devkor/com/teamcback/global/security/SecurityConfig.java
비회원 건의 작성 가능하도록 수정
- SecurityConfig에서 api/suggestions 허용
- 비회원인 경우 User를 null로 건의 저장
-
=> 비회원 건의 작성 가능하도록 수정

src/main/java/devkor/com/teamcback/domain/routes/service/RouteService.java, src/main/java/devkor/com/teamcback/global/exception/GlobalExceptionHandler.java
노드 관리를 위한 예외 클래스를 만들었는데 예외 처리를 하지 않았어서 추가합니다!
swagger 등으로 어떤 노드에서 오류가 나는지 확인하기 위해 추가한 거라 FE에는 영향이 없을 것 같습니다.
- AdminException 핸들러 추가, data 필드에 AdminMessage 반환 추가
- 사용하지 않는 메서드 삭제
-
=> 노드 관리용 예외 처리 추가

src/main/java/devkor/com/teamcback/domain/routes/service/RouteService.java
기본 길탐색 셔틀 경로 제거
- 기존 코드의 getGraph에서는 condition이 없는 경우 building 기준으로 탐색하였는데, 이 경우 모든 노드를 다 탐색하게 되어 shuttle 노드까지 포함됩니다. findNodeWithConditions에서는 condition이 없는 경우에도 기본 탐색 노드들이 설정되기에, 무조건 findNodeWithConditions를 이용하여 노드 탐색하도록 수정하였습니다.
- findNodeWithConditions에서 condition에 null이 들어오는 경우(condition이 없는 경우) 오류를 방지하는 코드를 추가하였습니다.
=> Fix: 기본 길탐색 셔틀 경로 제거

src/main/java/devkor/com/teamcback/domain/building/repository/BuildingRepository.java, src/main/java/devkor/com/teamcback/domain/routes/service/RouteService.java
- 실내노드가 없을 때, 길찾기 오류가 발생하는 경우 수정 
- 하나의 Entrance가 2개의 Building과 연결되어 있는 경우는 없기 때문에 실외-실내의 연결을 찾는 것이 아닌, adjacentNodes 중 building에 해당하는 노드가 있는지 확인하는 방식으로 변경하였습니다.
- BuildingRepository에서 NativeQuery를 활용하여, Node 객체를 찾지 않고도 node_id 만으로도 조회할 수 있도록 하였습니다.
->총 DB 조회 횟수가 1번으로 줄어들었습니다.
- 시각적인 확인이 어려워 오류 여부만 확인했는데 다른 문제가 있다면 말씀주시면 감사하겠습니다!
=> Fix: 실내-실외 구분 오류 수정

src/main/java/devkor/com/teamcback/domain/user/validator/AppleValidator.java, src/main/java/devkor/com/teamcback/domain/user/validator/GoogleValidator.java, src/main/java/devkor/com/teamcback/domain/user/validator/KakaoValidator.java, src/main/java/devkor/com/teamcback/global/jwt/JwtAuthorizationFilter.java, src/main/java/devkor/com/teamcback/global/jwt/OIDC/OIDCUtil.java, src/main/java/devkor/com/teamcback/global/response/ResultCode.java, src/main/java/devkor/com/teamcback/global/security/UserDetailsServiceImpl.java
'권한없음' 예외 처리 중 FE에서 로그인 화면으로 돌아가는 예외 처리(유효하지 않은 토큰 등)와 실제로 권한이 없는 예외 처리(다른 사람의 즐겨찾기를 조회 등)를 구분하기 위해 전자를 유효하지 않은 토큰 예외 처리로 추가 및 수정했습니다.
한 사람이 여러 기기에서 로그인 한 후 하나에서 탈퇴했을 경우에도 로그인 처리하기 위해 토큰 내 userId에 해당하는 사용자가 없는 경우는 탈퇴 예외 처리로 수정했습니다.
- 유효하지 않은 토큰 예외 처리 추가(토큰 관련 권한 없음 예외 처리를 수정)
- 탈퇴한 사용자 예외 처리 추가(필터에서 토큰 userId에 해당하는 사용자가 없을 때를 수정)
-
=> Feat: 유효하지 않은 토큰, 탈퇴한 사용자 예외 처리 추가

src/main/java/devkor/com/teamcback/domain/user/validator/AppleValidator.java, src/main/java/devkor/com/teamcback/domain/user/validator/GoogleValidator.java, src/main/java/devkor/com/teamcback/domain/user/validator/KakaoValidator.java
throw한 예외를 제대로 처리하지 않은 부분이 있어서 수정합니다!
- 소셜 공개키가 일치하지 않는 경우에는 재로그인 요청 예외 처리를, 그 외 문제는 유효하지 않은 토큰 예외 처리를 하도록 수정
-
=> Fix: 예외 처리 오류 수정

src/main/java/devkor/com/teamcback/domain/bookmark/service/BookmarkService.java, src/main/java/devkor/com/teamcback/domain/bookmark/service/CategoryService.java, src/main/java/devkor/com/teamcback/global/exception/CustomAccessDeniedHandler.java, src/main/java/devkor/com/teamcback/global/exception/CustomAuthenticationEntryPoint.java, src/main/java/devkor/com/teamcback/global/response/ResultCode.java, src/main/java/devkor/com/teamcback/global/security/SecurityConfig.java
토큰이 없을 때 인증이 필요한 요청을 한 경우 예외 처리 요청이 있어 추가합니다.
- 401: 인증이 되지 않았을 때 인증이 필요한 경우
- 403: 인증이 되었지만 권한이 없는 경우
- 403용 예외 처리를 추가하여 기존 unauthorized 예외를 상황에 맞게 분리하였습니다.
-
=> 필터 인증 예외 처리 추가

src/main/java/devkor/com/teamcback/domain/routes/service/RouteService.java, src/test/java/devkor/com/teamcback/integration/RouteServiceIntegrationTest.java
첫 노드가 building인 경우, 노드가 아닌 첫 path를 삭제하는 오류가 있어서 수정하였습니다.
- 첫 노드 만을 지울 경우, 경로에 따라 빈리스트로 인한 오류가 발생하는 경우가 있어 case를 구분하였습니다.
- 전체 경로 확인 시간이 너무 오래 걸려 일단 빌딩-빌딩 경우의 테스트만 완료하였습니다. 다른 경로에서 문제가 발생한다면 말씀주시면 감사하겠습니다!
=> Fix: 길찾기 오류 수정

src/main/java/devkor/com/teamcback/global/exception/GlobalExceptionHandler.java, src/main/java/devkor/com/teamcback/global/response/ResultCode.java
중복된 값이 있는 경우, DB에 직접 넣어서 관리 프로그램 통해서 데이터를 넣을 때 입력 오류가 나는 경우 등이 401 예외로 나와 구분하기 힘들어 관리를 위해 예외 처리 추가했습니다.
- DB 관련 오류를 핸들링하고 에러 메시지를 반환하도록 추가
-
=> DB 관련 오류 예외 처리

src/main/java/devkor/com/teamcback/domain/user/validator/AppleValidator.java, src/main/java/devkor/com/teamcback/domain/user/validator/GoogleValidator.java, src/main/java/devkor/com/teamcback/domain/user/validator/KakaoValidator.java, src/main/java/devkor/com/teamcback/domain/user/validator/client/AppleClient.java, src/main/java/devkor/com/teamcback/global/redis/RedisUtil.java
소셜 로그인 예외 처리 수정
- 애플 캐싱 데이터 키 값 설정
- 소셜 예외 처리 오류 수정
- 캐싱된 값이 일치하지 않을 경우 기존 값을 삭제하도록 수정
-
=> Fix: 소셜 로그인 예외 처리 수정

src/main/java/devkor/com/teamcback/domain/routes/service/RouteService.java
cutRoute 버그 패치
- 층 이동 도중에 건물을 이동해버리면 cutRoute에서 감지되지 않는 오류 수정
- 층 연속이동 후 count++가 한번 더 일어나는 것을 방지하기 위해 count-- 추가
=> Fix: cutRoute 버그 패치

build.gradle, src/main/java/devkor/com/teamcback/domain/operatingtime/scheduler/HolidayScheduler.java, src/main/java/devkor/com/teamcback/domain/operatingtime/scheduler/OperatingScheduler.java, src/main/java/devkor/com/teamcback/global/redis/RedisConfig.java, src/main/java/devkor/com/teamcback/global/redis/RedisLockUtil.java, src/test/java/devkor/com/teamcback/RedissonLockTest.java, src/test/java/devkor/com/teamcback/RedissonMultiThreadTest.java
여러 서버가 동일한 시간에 동일한 데이터에 대하여 운영 시간 스케줄러를 실행하는 것을 막기 위해 분산 락을 추가했습니다.
- Redis를 이용한 네임드 락을 지원하는 Redisson 사용하여 스케줄러 작동 시 특정 키값을 가진 락을 설정함으로써 서버 1대에서만 스케줄러가 작동하도록 함
- 테스트 코드는 gpt의 도움을 받았습니다. (주석처리함)
- commit을 잘못해서 엉망진창입니다...
=> 운영 시간 스케줄러를 위한 분산 락 설정

build.gradle, src/main/java/devkor/com/teamcback/domain/user/service/UserService.java, src/main/java/devkor/com/teamcback/global/response/ResultCode.java
별명 수정 시 비속어 확인 추가
- 별명 유효성 검증 메서드에 비속어가 있으면 예외를 던지도록 추가했습니다.
- 사용한 라이브러리: https://github.com/VaneProject/bad-word-filtering
=> Feat: 별명 수정 시 비속어 확인 추가

src/main/java/devkor/com/teamcback/domain/suggestion/controller/SuggestionController.java
Swagger 건의 사진 입력 가능하도록 수정
- SuggestionContoller에 consumes = MediaType.MULTIPART_FORM_DATA_VALUE를 추가하여 여러 이미지를 Swagger에서 입력 가능하도록 수정했습니다.
-
=> Docs: Swagger 건의 사진 입력 가능하도록 수정

build.gradle, src/main/java/devkor/com/teamcback/domain/bookmark/dto/request/CreateBookmarkReq.java, src/main/java/devkor/com/teamcback/domain/bookmark/service/BookmarkService.java, src/main/java/devkor/com/teamcback/domain/suggestion/dto/request/CreateSuggestionReq.java, src/main/java/devkor/com/teamcback/domain/suggestion/service/SuggestionService.java, src/main/java/devkor/com/teamcback/domain/user/dto/response/GetUserInfoRes.java, src/main/java/devkor/com/teamcback/domain/user/entity/User.java, src/main/java/devkor/com/teamcback/domain/user/service/UserService.java, src/main/java/devkor/com/teamcback/global/annotation/UpdateScore.java, src/main/java/devkor/com/teamcback/global/aop/UpdateScoreAspect.java, src/test/java/devkor/com/teamcback/global/aop/UpdateScoreAspectTest.java
- 유저 Score 증가 로직을 AOP로 수정하였습니다.
- 건의함 추가 : 항상 증가
- 북마크 추가 :  로그가 존재하지 않으면 증가
- tb_user 테이블에 isUpgraded 필드를 추가하여 레벨업 팝업 여부를 판단할 수 있도록 수정하였습니다.
- 마이페이지 조회 API에 isUpgraded 필드를 추가하였습니다.
- 점수 증가 기준을 메소드 단위로 적용하는 것이 편할 것 같아서 커스텀 어노테이션을 제작하였습니다. `@UpdateScore` 이 붙은 경우 AOP가 적용됩니다.
- 어노테이션 내부의 addScore 필드를 통해 증가시키고 싶은 값을 유동적으로 받아올 수 있습니다.
(이전)
- 점수 증가 여부가 내부 로직에 따라 달라지는 경우가 있어 Advice를 2가지로 작성하였습니다. (`@Before`, `@AfterReturning`)
- 전체 흐름
- `@Before` 로 호출 전 필요 정보를 필드에 저장 + 점수 증가 여부 확인
- 비즈니스 로직 수행
- 검사 플래그(needUpdate) 가 true인 경우에만 점수 증가 로직을 수행
(수정 후)
- `@Around`로 호출 전/후 로직 통합
- 만약 점수 증가 후 레벨이 달라진다면, isUpgraded를 true로 갱신합니다.
- 이후 마이페이지 조회 API를 호출하면, 해당 값을 추가적으로 반환하고 isUpgraded를 다시 false로 갱신합니다. (일회성)
- 제가 아직 테스트 코드에 익숙하지 않아서 검사 로직이 지저분하고 길어졌는데 더 나은 방법이 있다면 말씀주시면 감사하겠습니다!
=> Fix : 유저 Score 증가 로직 AOP 적용

build.gradle, src/main/java/devkor/com/teamcback/global/config/WebConfig.java, src/main/java/devkor/com/teamcback/infra/cloudwatch/CloudWatchConfig.java, src/main/java/devkor/com/teamcback/infra/cloudwatch/MetricsInterceptor.java, src/main/java/devkor/com/teamcback/infra/cloudwatch/MetricsService.java, src/main/resources/application.yml
cloudwatch api별 요청 횟수 지표 추가
- cloudwatch에 uri별 요청 횟수를 1분마다 전송하도록 설정 -> cloudwatch 대시보드에서 확인 가능
- 특정 서버에서만 보내기 위해 application.yml 값 추가
- 비용을 줄이기 위해 지표 uri을 제한(제 생각에 주요 uri를 적어봤는데 추가/삭제해도 좋은 uri 있으면 수정하셔도 됩니다!), uri 정규화 (building/123 -> building/{buildingId} 등)
- 따로 프로메테우스, 그라파나 컨테이너를 띄우는 것보다 cloudwatch를 사용하는게 더 간단하고 비용도 줄일 수 있을 것 같아서 적용해보았습니다.
- 저도 처음 해보는 거라 한번 개발 서버에서 확인해보고 배포 서버로 수정해야 할 것 같아요!
=> Feat: cloudwatch api별 요청 횟수 지표 추가

src/main/java/devkor/com/teamcback/infra/cloudwatch/MetricsService.java
개발 서버 테스트 후 배포 서버인 경우에만 metric을 보내도록 수정했습니다.
- 적용 대상을 배포 서버로 변경
- 보낼 메트릭 없으면 객체 생성하지 않고 바로 return하도록 수정
-
=> Fix: 배포 서버로 적용 변경

src/main/java/devkor/com/teamcback/domain/search/contoller/SearchController.java, src/main/java/devkor/com/teamcback/global/jwt/JwtAuthorizationFilter.java
건물, 장소 검색 시 즐겨찾기 여부 반환 오류 수정
- 예전에 토큰이 이상해도 오류나지 않도록 search api를 화이트리스트에 등록했었는데 그것 때문에 사용자 정보가 안들어가서 오류가 났네요.. 그래서 장소, 건물 검색은 제외하고 화이트리스트를 수정했습니다.
-
=> Fix: 검색 시 즐겨찾기 여부 반환 오류 수정

src/main/java/devkor/com/teamcback/domain/koyeon/dto/response/SearchFreePubRes.java, src/main/java/devkor/com/teamcback/domain/koyeon/service/KoyeonService.java
pub 정보 DTO 수정
- 무료 주점 리스트 반환 시 menu/주소를 함께 반환하도록 수정했습니다.
``` json
{
"menus": [
"제육볶음",
"전",
"오뎅탕"
],
"id": 48,
"name": "왕빈대떡삼파전",
"sponsor": "뉴욕 교우회",
"operatingTime": null,
"longitude": 127.0298492,
"latitude": 37.5858241,
"nodeId": 25213,
"address": "서울특별시 성북구 고려대로26길 8"
},
```
-
=> Fix: 무료주점 DTO 수정
