src/main/java/devkor/com/teamcback/domain/navigate/controller/RouteController.java, src/main/java/devkor/com/teamcback/domain/navigate/dto/response/DijkstraRes.java, src/main/java/devkor/com/teamcback/domain/navigate/dto/response/GetGraphRes.java, src/main/java/devkor/com/teamcback/domain/navigate/dto/response/GetRouteRes.java, src/main/java/devkor/com/teamcback/domain/navigate/dto/response/PartialRouteRes.java, src/main/java/devkor/com/teamcback/domain/navigate/entity/LocationType.java, src/main/java/devkor/com/teamcback/domain/navigate/entity/Node.java, src/main/java/devkor/com/teamcback/domain/navigate/repository/NodeRepository.java, src/main/java/devkor/com/teamcback/domain/navigate/service/RouteService.java
통합 경로탐색 api 추가
api/routes경로로 경로 제공
swagger로 필요 parameter 명세 제공
추후 작업으로 오류 발생 시 exception handling, 리팩토링, 시간 이슈 관련 수정 예정
=> Feat: 경로탐색 api 추가

src/main/java/devkor/com/teamcback/domain/navigate/service/RouteService.java
경로탐색 오류 수정
경로 파싱 관련사항 수정(cutRoute), 경로 미제공 조건 수정
=> fix: 경로탐색 오류수정 및 경로 미제공 오류 수정

src/main/java/devkor/com/teamcback/domain/classroom/entity/Classroom.java, src/main/java/devkor/com/teamcback/domain/facility/entity/Facility.java, src/main/java/devkor/com/teamcback/domain/search/dto/response/GetRoomDetailRes.java
상윤님이 요청하신 maskIndex 칼럼 추가했습니다.
- classroom과 facility에 칼럼 maskIndex를 추가했습니다.
-
=> Fix: 건물 층별 장소 조회 maskIndex 추가

src/main/java/devkor/com/teamcback/domain/bookmark/controller/CategoryController.java, src/main/java/devkor/com/teamcback/domain/bookmark/dto/request/CreateBookmarkReq.java, src/main/java/devkor/com/teamcback/domain/bookmark/dto/request/ModifyBookmarkReq.java, src/main/java/devkor/com/teamcback/domain/bookmark/dto/response/CreateBookmarkRes.java, src/main/java/devkor/com/teamcback/domain/bookmark/dto/response/DeleteBookmarkRes.java, src/main/java/devkor/com/teamcback/domain/bookmark/dto/response/GetBookmarkRes.java, src/main/java/devkor/com/teamcback/domain/bookmark/dto/response/GetCategoryRes.java, src/main/java/devkor/com/teamcback/domain/bookmark/dto/response/ModifyBookmarkRes.java, src/main/java/devkor/com/teamcback/domain/bookmark/entity/Bookmark.java, src/main/java/devkor/com/teamcback/domain/bookmark/entity/Category.java, src/main/java/devkor/com/teamcback/domain/bookmark/entity/PlaceType.java, src/main/java/devkor/com/teamcback/domain/bookmark/repository/BookmarkRepository.java, src/main/java/devkor/com/teamcback/domain/bookmark/repository/CategoryRepository.java, src/main/java/devkor/com/teamcback/domain/bookmark/service/CategoryService.java, src/main/java/devkor/com/teamcback/global/response/ResultCode.java
- 카테고리 목록 조회
- 특정 카테고리의 즐겨찾기 List 조회
- 즐겨찾기 생성
- 즐겨찾기 삭제
- 즐겨찾기 수정
- 즐겨찾기 조회 (특정 즐겨찾기)
- merge하기 전에 잘 돌아가는지 확인 한번만 해주시면 감사하겠습니다!!
=> 즐겨찾기 기능 & 카테고리 조회 기능 추가

src/main/java/devkor/com/teamcback/domain/building/entity/Building.java, src/main/java/devkor/com/teamcback/domain/facility/repository/FacilityRepository.java, src/main/java/devkor/com/teamcback/domain/search/dto/response/SearchFacilityRes.java, src/main/java/devkor/com/teamcback/domain/search/service/SearchService.java
화장실 검색 시 다른 화장실(여자,남자,장애인)도 검색되도록, 여자/남자 화장실 검색 시 여자/남자 장애인 화장실도 검색되도록 수정했습니다.
그 외 오류 수정했습니다.
- 화장실 수정: 검색어 자동완성 api, 편의시설이 있는 건물 리스트 조회 api
- 오류 수정
- 건물, 검색어에 해당하는 편의시설 검색 시 건물 조건이 제대로 반영 안됨
- 편의시설에 해당하는 건물 리스트 조회 시 건물 중복 문제 -> equals(), hashCode() 메서드 오버라이딩
- 편의시설 검색 시 detail 추가
- 그 외
- public, private 메소드 순으로 정리했습니다!
-
=> Fix: 화장실 검색 수정 및 편의시설 검색 오류 수정

src/main/java/devkor/com/teamcback/domain/facility/entity/FacilityType.java
- TUMBLER_WASHER("텀블러세척기"), ONESTOP_AUTO_MACHINE("원스탑무인발급기") 추가
=> FacilityType 추가

src/main/java/devkor/com/teamcback/domain/search/dto/response/SearchBuildingRes.java, src/main/java/devkor/com/teamcback/domain/search/service/SearchService.java
=> 반환 건물에 야외 추가

src/main/java/devkor/com/teamcback/domain/operatingtime/service/OperatingService.java
운영 여부가 DB에 제대로 반영이 안되는 오류 수정
- 운영 여부가 DB에 제대로 반영이 안되는 오류 수정
- 운영 조건에 포함되지 않는 강의실, 편의시설 업데이트 중복 삭제
- 블로그에 정리해보았으니 참고해주세요! (https://jinjinjincode.tistory.com/314)
-
=> Fix: 운영시간 오류 수정

src/main/java/devkor/com/teamcback/domain/navigate/dto/response/GetRouteRes.java, src/main/java/devkor/com/teamcback/domain/navigate/entity/BuildingIds.java, src/main/java/devkor/com/teamcback/domain/navigate/entity/Checkpoint.java, src/main/java/devkor/com/teamcback/domain/navigate/entity/LinkedBuildingData.java, src/main/java/devkor/com/teamcback/domain/navigate/repository/CheckpointRepository.java, src/main/java/devkor/com/teamcback/domain/navigate/service/RouteService.java, src/main/java/devkor/com/teamcback/global/response/ResultCode.java
경로 분할 및 거리 설정(100% 완성은 아님)
-체크포인트 기반 경로 분할 기능 추가
-coord기반 경로 탐색 시, 출발지/도착지가 캠퍼스에서 너무 멀면 에러코드 6003 리턴
-노드 관련 에러코드(길찾기 시)는 오늘 내 추가 예정, 다음 커밋때 추가
-
=> Feat: 경로 분할 및 거리 설정

src/main/java/devkor/com/teamcback/domain/navigate/service/RouteService.java, src/main/java/devkor/com/teamcback/global/response/ResultCode.java
경로탐색 오류 수정, 에러핸들링 추가
- 찾는 시설이 운영중이지 않을 때 에러핸들링 추가
- adjacentNode와 distance가 null이 아닌 빈 str일때 경로탐색이 되지 않는 현상 수정
-
=> Fix: 경로탐색 오류 수정

src/main/java/devkor/com/teamcback/domain/navigate/service/RouteService.java
길찾기 층 설명 -1 -> B1로 수정
- 길찾기 경로에서 지하 층의 경우 -1 -> B1 로 수정
-
=> Fix: 길찾기 층 설명 -1 -> B1로 수정

src/main/java/devkor/com/teamcback/domain/search/contoller/SearchController.java, src/main/java/devkor/com/teamcback/domain/search/service/SearchService.java
- swagger의 변수명 변겅 (type -> placeType)
- 건물 내 편의시설 목록을 가져오는 경우, CLASSROOM 제외하도록 filter 추가
=> fix: search 오류 수정

src/main/java/devkor/com/teamcback/domain/operatingtime/entity/OperatingCondition.java, src/main/java/devkor/com/teamcback/domain/operatingtime/sceduler/OperatingScheduler.java, src/main/java/devkor/com/teamcback/domain/operatingtime/service/OperatingService.java, src/main/java/devkor/com/teamcback/domain/search/contoller/SearchController.java, src/main/java/devkor/com/teamcback/domain/search/service/SearchService.java
Place 추가에 따른 스케줄러 수정
- DB에 운영 조건 테이블만 수정하고 코드는 거의 그대로 입니다!
- 스케줄러가 서버 수정으로 시작될 때마다 바로 작동할 수 있도록 추가 설정
-
=> Fix: 스케줄러 수정

src/main/java/devkor/com/teamcback/infra/s3/FilePath.java, src/main/resources/application.yml
FilePath 및 기본 이미지 url 수정
- FilePath: classroom -> place 수정
- 기본 이미지 url 수정
-
=> Fix/s3 FilePath 및 기본 이미지 url 수정

src/main/java/devkor/com/teamcback/infra/s3/FilePath.java, src/main/resources/application.yml
s3 수정 관련 내용 반영
- FilePath classroom -> place
- 기본 이미지 url 수정
-
=> s3 수정 관련 내용 반영

src/main/java/devkor/com/teamcback/domain/operatingtime/service/OperatingService.java
운영 조건이 있는 장소를 저장하는 정적 변수 제거
- 관련 데이터가 자꾸 복구되는 것 같아 정적 변수를 제거합니다!
-
=> Fix: 정적 변수 제거

src/main/java/devkor/com/teamcback/domain/place/dto/request/CreatePlaceReq.java, src/main/java/devkor/com/teamcback/domain/place/dto/request/ModifyPlaceReq.java, src/main/java/devkor/com/teamcback/domain/place/dto/response/GetPlaceRes.java, src/main/java/devkor/com/teamcback/domain/place/entity/Place.java, src/main/java/devkor/com/teamcback/domain/place/entity/PlaceImage.java, src/main/java/devkor/com/teamcback/domain/place/repository/PlaceImageRepository.java, src/main/java/devkor/com/teamcback/domain/search/dto/response/SearchFacilityRes.java, src/main/java/devkor/com/teamcback/domain/search/dto/response/SearchFacilityTypeRes.java, src/main/java/devkor/com/teamcback/domain/search/dto/response/SearchPlaceDetailRes.java, src/main/java/devkor/com/teamcback/domain/search/dto/response/SearchPlaceImageRes.java, src/main/java/devkor/com/teamcback/domain/search/dto/response/SearchPlaceRes.java, src/main/java/devkor/com/teamcback/domain/search/dto/response/SearchRoomDetailRes.java, src/main/java/devkor/com/teamcback/domain/search/service/SearchService.java
Place에 세부 정보(description), 리뷰 평점 합, 리뷰 평점 개수, 장소 사진 추가
- Place에 세부 정보(description), 리뷰 평점 합(starSum), 리뷰 평점 개수(starNum) 추가
- 리뷰 평점만 double로 저장하려고 했는데 부동소수점 문제로 조금씩 오류가 생길 것 같아 두 가지를 저장
- PlaceImage 테이블 생성하여 Place와 일대다 관계
- 관리자 장소 관련 API req에 description 추가 -> 관리자페이지에 추가해주셨으면 좋겠습니다..!
- 기타 장소 관련 Search API res에 description, 리뷰 평점 평균 추가
- 장소 상세 정보 조회에만 res에 장소 이미지 list 반환 추가
- 건물에도 동일하게 리뷰 기능을 추가한다면 리뷰 평점 합, 리뷰 평점 개수, 장소 사진(일대다)를 추가해야 할 것 같은데 정해지면 그 때 하겠습니다!
=> Feat: Place에 리뷰 평점, 이미지, 세부정보 추가

src/main/java/devkor/com/teamcback/domain/building/entity/Building.java, src/main/java/devkor/com/teamcback/domain/oauth2/handler/OAuth2LoginSuccessHandler.java, src/main/java/devkor/com/teamcback/domain/operatingtime/sceduler/OperatingScheduler.java, src/main/java/devkor/com/teamcback/domain/operatingtime/service/OperatingService.java, src/main/java/devkor/com/teamcback/domain/place/dto/response/GetPlaceRes.java, src/main/java/devkor/com/teamcback/domain/search/dto/response/SearchFacilityRes.java, src/main/java/devkor/com/teamcback/domain/search/dto/response/SearchPlaceDetailRes.java, src/main/java/devkor/com/teamcback/domain/search/dto/response/SearchPlaceRes.java, src/main/java/devkor/com/teamcback/domain/search/dto/response/SearchRoomDetailRes.java
=> Fix/social login 테스트용 PR

src/main/java/devkor/com/teamcback/domain/user/controller/UserController.java, src/main/java/devkor/com/teamcback/domain/user/dto/request/LoginUserReq.java, src/main/java/devkor/com/teamcback/domain/user/dto/response/LoginUserRes.java, src/main/java/devkor/com/teamcback/domain/user/entity/User.java, src/main/java/devkor/com/teamcback/domain/user/service/UserService.java
=> Feat: 임시 로그인 메서드

src/main/java/devkor/com/teamcback/global/security/SecurityConfig.java
=> Feat: 로그인 접근 허용

src/main/java/devkor/com/teamcback/global/security/SecurityConfig.java
=> Fix: 오타 수정

src/main/java/devkor/com/teamcback/domain/operatingtime/sceduler/OperatingScheduler.java, src/main/java/devkor/com/teamcback/domain/operatingtime/service/OperatingService.java, src/main/java/devkor/com/teamcback/domain/place/entity/Place.java
운영시간 코드 리팩토링
- 주석 추가
- 메서드가 한 가지 기능만 하도록 리팩토링
-
=> 운영시간 코드 리팩토링

src/main/java/devkor/com/teamcback/domain/search/dto/response/SearchBuildingFacilityListRes.java, src/main/java/devkor/com/teamcback/domain/search/dto/response/SearchFacilityRes.java, src/main/java/devkor/com/teamcback/domain/search/dto/response/SearchPlaceRes.java, src/main/java/devkor/com/teamcback/domain/search/service/SearchService.java
- FE 요청으로 아래 두 API 반환 DTO에 placeType을 추가하였습니다.
- search/buildings/{buildingId}/facilities
- search/facilities
- search/buildings/{buildingId}/facilities
- 여기서 반환 변수 중 facilities가 HashMap으로 되어있던데 혹시 일반 List로 반환하는 것과 차이가 있나요?? 코드 읽다가 궁금해져서 여쭤봅니다..!!
=> Fix: DTO 수정

src/main/java/devkor/com/teamcback/domain/routes/repository/NodeRepository.java, src/main/java/devkor/com/teamcback/domain/search/dto/response/SearchNodeRes.java, src/main/java/devkor/com/teamcback/domain/search/dto/response/SearchRoomRes.java, src/main/java/devkor/com/teamcback/domain/search/service/SearchService.java
출입구, 계단, 엘베 정보도 반환
- 건물 층별 조회 시 출입구, 계단, 엘베 정보도 반환하도록 수정
- 화장실은 기존에도 있어서 나머지만 수정했습니다.
- Place와 달리 노드 그 자체여서 새로 dto를 만들었습니다.
=> Feat: 출입구, 계단, 엘베 정보도 반환

src/main/java/devkor/com/teamcback/domain/search/dto/response/SearchFacilityRes.java
FE요청으로 facilityId -> id로 변수명을 수정하였습니다.
최대한 빠른 수정을 요청하셔서 확인하시면 바로 머지 부탁드리겠습니다!
=> Fix: 변수명 수정

src/main/java/devkor/com/teamcback/domain/search/dto/request/SaveSearchLogReq.java, src/main/java/devkor/com/teamcback/domain/search/dto/response/SearchLogRes.java, src/main/java/devkor/com/teamcback/domain/search/entity/SearchLog.java, src/main/java/devkor/com/teamcback/domain/search/service/SearchService.java
SearchLog 및 dto 수정
-  SearchLog 및 dto를 globalSearch의 dto와 동일하도록 수정했습니다.
-
=> Fix: SearchLog 및 dto 수정

src/main/java/devkor/com/teamcback/domain/bookmark/controller/CategoryController.java
카테고리 조회 파라미터 required=false 추가
- 카테고리 조회 파라미터 required=false 추가
-
=> Fix: 카테고리 조회 파라미터 required=false 추가

src/main/java/devkor/com/teamcback/domain/user/repository/UserRepository.java, src/main/java/devkor/com/teamcback/domain/user/service/UserService.java, src/main/java/devkor/com/teamcback/global/jwt/JwtAuthorizationFilter.java, src/main/java/devkor/com/teamcback/global/jwt/JwtUtil.java, src/main/java/devkor/com/teamcback/global/security/UserDetailsServiceImpl.java
토큰을 userId로 발급하도록 수정
- 닉네임 변경 문제로 인해 토큰을 userId로 발급하도록 수정
-
=> Fix: 토큰을 userId로 발급하도록 수정

src/main/java/devkor/com/teamcback/domain/bookmark/repository/CategoryRepository.java, src/main/java/devkor/com/teamcback/domain/search/contoller/SearchController.java, src/main/java/devkor/com/teamcback/domain/search/dto/response/GlobalSearchRes.java, src/main/java/devkor/com/teamcback/domain/search/service/SearchService.java
통합 검색 수정
- 내부태그 효과를 가지는 건물명+시설 타입명 에서 일부 타입들을 제거한 결과를 내도록 수정하였습니다.
→ 필터링된 타입들: 'CLASSROOM', 'TOILET', 'MEN_TOILET', 'WOMEN_TOILET', 'MEN_HANDICAPPED_TOILET', 'WOMEN_HANDICAPPED_TOILET', 'LOCKER', 'TRASH_CAN'
- 로그인된 상태로 검색을 하는 경우, 즐겨찾기한 결과가 맨 위에 뜨도록 수정하였습니다.
→ 반환 타입에 isBookmarked, categoryColor 추가
=> Fix: 통합 검색 수정

src/main/java/devkor/com/teamcback/domain/user/service/UserService.java
=> Fix: refreshToken 오류 수정

src/main/java/devkor/com/teamcback/domain/search/dto/response/SearchMainFacilityRes.java, src/main/java/devkor/com/teamcback/domain/search/service/SearchService.java
- 클릭 시 연결되지 않는 편의시설 타입들을 검색 결과에서 제외
- 건물 상세 정보 조회 -> DTO에 type의 한글 이름을 추가적으로 반환
=> Fix: 통합검색 수정

src/main/java/devkor/com/teamcback/domain/bookmark/entity/Category.java, src/main/java/devkor/com/teamcback/domain/user/service/UserService.java
새로 가입하는 회원의 기본 카테고리 자동 저장 추가
- 새로 가입하는 회원의 기본 카테고리 자동 저장 추가
-
=> Feat: 기본 카테고리 자동 저장 추가

src/main/java/devkor/com/teamcback/domain/user/dto/response/GetUserInfoRes.java, src/main/java/devkor/com/teamcback/domain/user/entity/Level.java, src/main/java/devkor/com/teamcback/domain/user/service/UserService.java
마이페이지 응답에 레벨 관련 필드 추가
- 다음 레벨까지 남은 점수 (최종 레벨이면 0) 추가
- 현재 레벨 점수 퍼센트 (최종레벨이면 100) 추가
-
=> 마이페이지 응답에 레벨 관련 필드 추가

src/main/java/devkor/com/teamcback/domain/search/service/SearchService.java
- 통합 검색 결과에서 자전거보관소, 벤치 제거 (KOYEON은 차후 완전 제거 예정)
=> Fix: 통함검색 필터 추가

src/main/java/devkor/com/teamcback/domain/search/service/SearchService.java, src/main/java/devkor/com/teamcback/global/security/SecurityConfig.java
=> API 권한 제한 추가

src/main/java/devkor/com/teamcback/domain/koyeon/dto/response/SearchFreePubInfoRes.java, src/main/java/devkor/com/teamcback/domain/koyeon/dto/response/SearchFreePubRes.java, src/main/java/devkor/com/teamcback/domain/koyeon/entity/FreePub.java
노드가 아닌 pub 자체의 위경도를 반환하도록 수정하였습니다
- 내용을 적어주세요.
-
=> Fix: 주점 위경도 좌표 수정 

src/main/java/devkor/com/teamcback/domain/koyeon/dto/response/SearchFreePubInfoRes.java, src/main/java/devkor/com/teamcback/domain/koyeon/entity/FreePub.java
메뉴 list가 null이 아닌 경우에만 split하도록 수정하였습니다.
- 내용을 적어주세요.
-
=> Fix: 주점 오류 수정

src/main/java/devkor/com/teamcback/domain/koyeon/controller/KoyeonController.java, src/main/java/devkor/com/teamcback/domain/koyeon/dto/response/GlobalPubSearchListRes.java, src/main/java/devkor/com/teamcback/domain/koyeon/dto/response/GlobalPubSearchRes.java, src/main/java/devkor/com/teamcback/domain/koyeon/dto/response/SearchFreePubInfoRes.java, src/main/java/devkor/com/teamcback/domain/koyeon/entity/FreePubNickname.java, src/main/java/devkor/com/teamcback/domain/koyeon/repository/FreePubNicknameRepository.java, src/main/java/devkor/com/teamcback/domain/koyeon/repository/MenuRepository.java, src/main/java/devkor/com/teamcback/domain/koyeon/service/KoyeonService.java, src/main/java/devkor/com/teamcback/domain/search/dto/response/GlobalSearchRes.java
- 기존 검색 : 건물명+특수 편의시설명인 경우, buildingId=null이 되는 것을 수정
- 주점 전용 검색 API 구현
- 특정 주점 정보 반환: menuList가 아닌, tb_menu를 참조하도록 수정
- 주점 전용 검색 API가 RESTful한지 모르겠어서.. 더 좋은 아이디어 있다면 추천 부탁드리겠습니다!
=> Feat: 검색 기능 수정

src/main/java/devkor/com/teamcback/domain/search/dto/response/SearchBuildingDetailRes.java
building/{buildinId} API의 반환 DTO에 위/경도 값 추가
- 내용을 적어주세요.
-
=> Fix: 건물 상세 정보 DTO 수정

src/main/java/devkor/com/teamcback/domain/routes/controller/RouteController.java, src/main/java/devkor/com/teamcback/domain/routes/entity/Conditions.java, src/main/java/devkor/com/teamcback/domain/routes/repository/NodeRepository.java, src/main/java/devkor/com/teamcback/domain/routes/service/RouteService.java
presentation용 barrierfree경로 추가
- 추후 condition 받을 수 있도록 리스트형 parameter 추가
- 무조건 배리어프리 기능 활성화한 경로 하나 추가
- condition 엔티티 추가
-
=> presentation용 barrierfree경로 추가

src/main/java/devkor/com/teamcback/domain/user/entity/Provider.java
Provider 애플 추가
- Provider 애플 추가
-
=> Feat: Provider 애플 추가

src/main/java/devkor/com/teamcback/domain/place/entity/Place.java, src/main/java/devkor/com/teamcback/domain/search/entity/DefaultPlace.java, src/main/java/devkor/com/teamcback/domain/search/service/SearchService.java, src/main/java/devkor/com/teamcback/global/response/ResultCode.java, src/main/resources/application.yml
건물 상세 모달 - 이미지가 null인 경우 기본 이미지를 반환하도록 수정하였습니다.
- 기본 이미지 적용 편의시설 : CAFE, CAFETERIA, CONVENIENCE_STORE, GYM, LOUNGE, READING_ROOM, SHOWER_ROOM, SLEEPING_ROOM, STUDY_ROOM
-
=> Fix: 건물 상세 기본 이미지 설정

src/main/java/devkor/com/teamcback/domain/user/controller/UserController.java, src/main/java/devkor/com/teamcback/domain/user/dto/response/TempLoginRes.java, src/main/java/devkor/com/teamcback/domain/user/service/UserService.java
안드로이드을 고려해서 이전 버전 로그인용 response 항목을 유지하도록 임시 dto를 추가했습니다.
- 이전 버전 로그인용 TempLoginRes 추가
-
=> 이전 버전 로그인용 임시 resDto 수정

src/main/java/devkor/com/teamcback/domain/search/service/SearchService.java
검색 기능 오류를 수정하였습니다.
- "지리교육학과 학생회실"과 같이 공백을 포함하지만 하나의 검색어가 될 수 있는 경우를 포함하였습니다.
- 다른 문제가 있다면 편하게 말씀주세요!
=> fix: 공백 포함 단일 검색어 오류 수정

src/main/java/devkor/com/teamcback/domain/common/LocationType.java, src/main/java/devkor/com/teamcback/domain/search/dto/response/GlobalSearchRes.java, src/main/java/devkor/com/teamcback/domain/search/service/SearchService.java
프런트 요청 반영 및 오류 수정
- 외부 태그와 동일한 효과가 필요한 경우, LocationType을 Facility로 설정하였습니다.
- placeName과 placeType의 이름이 동일한 경우, 장소가 뜨지 않는 오류를 수정하였습니다.
-
=> Fix: 검색 기능 수정

src/main/java/devkor/com/teamcback/domain/migration/controller/MigrationController.java, src/main/java/devkor/com/teamcback/domain/migration/entity/Migration.java, src/main/java/devkor/com/teamcback/domain/migration/repository/MigrationRepository.java, src/main/java/devkor/com/teamcback/domain/migration/service/MigrationService.java, src/main/java/devkor/com/teamcback/global/response/ResultCode.java
Migration 관련 API를 추가하였습니다.
-> api/migration
- DB에 tb_migration을 추가하였습니다.
- id = 1의 isMigrating 값을 반환합니다.
- 따로 예외 번호대를 할당하기 애매하다고 생각해 특수 번호에 넣어두었습니다. 다른 의견 있으시면 편하게 말씀주세요!
=> feat: 스토어 이전 여부 반환 API 추가

src/main/java/devkor/com/teamcback/domain/user/validator/AppleValidator.java, src/main/java/devkor/com/teamcback/global/jwt/OIDC/OIDCUtil.java, src/main/resources/application.yml
애플 토큰 검증 과정에서 사용하는 aud가 2개라서 발생하는 오류 수정
- 다른 aud를 application.yml에 추가하고 노션에 추가해놨습니다!
-
=> Fix: 애플 dev-aud 추가

src/main/java/devkor/com/teamcback/global/jwt/JwtAuthorizationFilter.java
FE 비회원 기능 개발을 위해 토큰이 필요 없는 요청은 토큰이 유효하지 않아도 응답이 오도록 수정
- authorizationFilter에 shouldNotFilter 메서드로 화이트리스트를 추가
-
=> Feat: authorizationFilter에 화이트리스트 추가

src/main/java/devkor/com/teamcback/domain/routes/repository/NodeRepository.java, src/main/java/devkor/com/teamcback/domain/suggestion/dto/response/GetSuggestionRes.java, src/test/java/devkor/com/teamcback/integration/RouteServiceIntegrationTest.java
건의 조회 오류 수정
- 건의 조회 시 비회원인 경우 사용자가 null이어서 발생하는 오류 수정
- 테스트 코드 길찾기 노드를 무작위 20개만 가져오도록 수정
-
=> 건의 조회 오류 수정

.github/workflows/aws.yml
ecs cicd를 위한 yml 테스트
- ecs cicd를 위한 aws.yml 추가
-
=> ecs cicd를 위한 yml

.github/workflows/aws.yml
task-definition을 시크릿에 추가
- aws.yml 수정
-
=> task-definition을 시크릿에 추가

.github/workflows/aws.yml
=> Dockerfile로 빌드

.github/workflows/aws.yml
시크릿 이용하여 task-definition.json 사용
- aws.yml 수정
-
=> 시크릿 이용하여 task-definition.json 사용

.github/workflows/aws.yml
=> .aws 디렉토리 생성

.github/workflows/aws.yml
=> main용 cd로 수정

.github/workflows/aws-dev.yml
dev용 aws.yml 추가
- aws-dev.yml 추가
-
=> dev용 aws.yml 추가

src/main/java/devkor/com/teamcback/domain/operatingtime/scheduler/OperatingScheduler.java
스케줄러가 반영안되는 이유를 자세히 봐야 할 것 같아서 일단 테스트용으로 올립니다!
- 스케줄러마다 setState() 추가
-
=> 스케줄러 임시 수정

.github/workflows/aws-dev.yml, src/main/java/devkor/com/teamcback/domain/operatingtime/scheduler/OperatingScheduler.java
=> main -> develop

src/main/java/devkor/com/teamcback/domain/suggestion/controller/SuggestionController.java, src/main/java/devkor/com/teamcback/domain/suggestion/dto/request/CreateSuggestionReq.java, src/main/java/devkor/com/teamcback/domain/suggestion/entity/Suggestion.java, src/main/java/devkor/com/teamcback/domain/suggestion/entity/SuggestionImage.java, src/main/java/devkor/com/teamcback/domain/suggestion/service/SuggestionService.java, src/main/java/devkor/com/teamcback/global/jwt/JwtAuthorizationFilter.java, src/main/java/devkor/com/teamcback/infra/s3/FilePath.java
건의 이메일, 사진 추가
- 건의 작성 req에 이메일을 추가하고 컨트롤러에서 사진을 추가로 받을 수 있도록 수정
-
=> 건의 이메일, 사진 추가

src/main/java/devkor/com/teamcback/domain/building/service/AdminBuildingNicknameService.java, src/main/java/devkor/com/teamcback/domain/place/entity/PlaceType.java, src/main/java/devkor/com/teamcback/domain/place/service/AdminPlaceNicknameService.java, src/main/java/devkor/com/teamcback/domain/search/service/SearchService.java, src/main/java/devkor/com/teamcback/domain/search/util/HangeulUtils.java
- 한글 Utils를 static 메소드들의 집합으로 수정
- PlaceType에 HEALTH_OFFICE 추가
- Utils의 경우, 빈으로 등록/관리하는 것이 아니라 static한 함수들로 단순 기능만 제공하는 것이 일반적이라 들어 해당 부분을 수정하였습니다. 기능적인 변화는 없습니다.
- DB에서 중지/하스의 건강센터를 HEALTH_OFFICE로 수정하고, 검색 결과에도 반영되도록 하였습니다.
- 건강센터 별명 관련 추가사항 있으면 최대한 많이 알려주시면 감사하겠습니다!
=> Refactor: Search 패키지 관련 리팩토링

.github/workflows/aws-dev.yml, build.gradle, src/main/resources/application.yml
프로메테우스와 그라파나를 적용하기 위해 필요한 코드 상 수정입니다.
- 의존성 추가 및 yml 파일 수정하였습니다.
- 배포 오류로 개발 관련 서비스를 재생성하는 김에 이름도 수정했습니다! (kodaero1 -> kodaero)
=> Feat: 모니터링 관련 설정 추가

src/main/resources/application.yml
변수로 해야 로컬, 개발, 배포 상황에 맞게 yml 파일을 하나로 사용할 수 있을 것 같아서 메트릭 적용할 서버를 환경변수로 변경했습니다!
- application.yml에 환경변수 추가 : 로컬에서는 dev로 설정해주세요!
-
=> Fix: application.yml 변수 적용

src/main/java/devkor/com/teamcback/infra/cloudwatch/MetricsService.java, src/main/resources/application.yml
main 브랜치 업데이트
- 지표 수집 관련 환경변수 추가
-
=> main <- develop

src/main/java/devkor/com/teamcback/domain/place/entity/PlaceType.java, src/main/java/devkor/com/teamcback/domain/search/service/SearchService.java
배리어 프리 출입문 / 공용 장애인 화장실 타입을 추가하였습니다. (코드 + DB)
- PlaceType에 BARRIER_FREE_ENTRANCE / HANDICAPPED_TOILET을 추가하였습니다.
- 배리어프리 출입문을 nodeList가 아닌 PlaceList에서 반환하도록 필터를 추가하였습니다.
-
=> [FIx] placeType 배리어프리 출입문 추가

src/main/java/devkor/com/teamcback/domain/search/service/SearchService.java
- 버전 불일치로 출입구가 일부 사라지는 오류 수정
- Entrance 필터링 부분을 주석처리하였습니다.
=> Fix: Entrance 필터링 주석 처리

src/main/java/devkor/com/teamcback/domain/place/entity/PlaceType.java, src/main/java/devkor/com/teamcback/domain/search/service/SearchService.java
=> develop -> main 병합

src/main/java/devkor/com/teamcback/domain/place/entity/PlaceType.java
다회용컵 반납함 추가
- placetype에 다회용컵 반납함 추가했습니다.
-
=> 다회용컵 반납함 추가

src/main/resources/application.yml
건의 수신 이메일 추가
- 건의 수신 이메일 추가
- 시간될 때 머지까지 해주시면 감사하겠습니다!
=> 건의 수신 이메일 추가

src/main/java/devkor/com/teamcback/domain/search/dto/response/SearchBuildingDetailRes.java, src/main/java/devkor/com/teamcback/domain/search/dto/response/SearchBuildingRes.java, src/main/java/devkor/com/teamcback/domain/search/service/SearchService.java
search 도메인의 일부 결과를 수정했습니다.
- 검색 결과에 쓰레기통 & 리필로드 태그가 등장하도록 수정했습니다.
- 모달에서 "서울캠퍼스" 단어를 제거했습니다.
=> Fix: Search 결과 수정
